### ISSUE TITLE
What Batter / Power Supply To Use?  Power Tool?  Wall Supply?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/moonrat#48]
Power tool batteries may be common world wide?
![image](https://github.com/PubInv/moonrat/assets/5836181/de5d2b01-c490-415d-ba75-311ac878b9b9)

Wall supplies too?

**Comment by ForrestErickson** [comment]
@RobertLRead ,
What do you know or have sources regarding the availability of power tool batteries in low income locations?

The Dewalt batter and adapter converter above would be a way to use such batteries that may be common where ever building happens.

Please advise,
Lee
cc: @melanielaporte

**Comment by RobertLRead** [comment]
I think this is an interesting idea. I assume these are at least as available as the 12V USB power banks which we were planning to use, and probably recharge faster. 

However, we have to be careful if power tool batteries are not standardized wrt voltage. If we go above 12V, we probably need to carefully manage the duty cycle of the power, because we want the heating to remain gentle---you don't want any thing very hot inside the incubation chamber, even if eventually the heat will even out, because a hot spot can sterilize the sample.

Also, USB-based charging is equally ubiquitous. So I'm unless power batteries are highly standardized, I'm not sure there is much advantage here. For example, when I was in Tanzania in the larger towns (Kigoma) you could by a full range of hardware, and I'm sure you could get drills. BUT I don't know that any one brand is completely ubiquitous across different nations; and if multiple brands are not interchangeable, that doesn't help us.

@ForrestErickson @melanielaporte

**Comment by melanielaporte** [comment]
@ForrestErickson @RobertLRead Does this topic need another discussion for PCB v2 design and order?

**Comment by melanielaporte** [comment]
@ForrestErickson @RobertLRead Does this topic need another discussion for the next design generation design?

**Comment by ForrestErickson** [comment]
Regarding, "Does this topic need another discussion for the next design generation design?"
I think not. At lease until we find that the batteries used by the Guadalajara team are hard to come by.

I suggest Melanie close this as will not fix.

**Comment by melanielaporte** [comment]
Will not do.
